### ISSUE TITLE
Is there any hope for support of mutable vectors instead of lists?

### ISSUE THREAD

**Issue by stgithubuser** [ekmett/discrimination#10]
I really love the library! It is very simple to use.

One thing was that sorting vectors of length 2000 proved to be at least 2-3 times slower than using a vector.
I have to use the Data-Vector-Algorithms package (https://hackage.haskell.org/package/vector-algorithms-0.7.0.1/docs/Data-Vector-Algorithms-Intro.html).

Would this extremely helpful library also work to sort mutable vectors quickly?

**Comment by phadej** [comment]
In my rough benchmarks `discrimination` for `[Word64]` is faster then `Data.List.sort` for lists over a million elements large. Sorting vectors of size 2000 will probably always be faster with introsort.
