### ISSUE TITLE
All the paper links 404

### ISSUE THREAD

**Issue by kozross** [ekmett/discrimination#17]
This includes Henglein's home page.

**Comment by lemastero** [comment]
They work for me. Probably the maintenance window. Cheers!

**Comment by gbaz** [comment]
All dead again?

**Comment by gwils** [comment]
Same for me

**Comment by kozross** [comment]
For once, it _does_ work for me.

**Comment by gwils** [comment]
It's working right now. I'm not sure what's going on.
