### ISSUE TITLE
"Group" Does Not Respect Eq

### ISSUE THREAD

**Issue by alexloomis** [ekmett/discrimination#20]
Given, eg
```haskell
newtype NewType = NewType (Int,Int)
instance Eq NewType where
    NewType (a,_) == NewType (b,_) = a == b
```
we have
__`> Data.List.group [NewType (0,0), NewType (0,1)]`__
`[[NewType (0,0), NewType (0,1)]]`
but
__`> Data.Discrimination.group [NewType (0,0), NewType (0,1)]`__
`[[NewType (0,0)], [NewType (0,1)]]`
Would it be possible to change the behavior to match `Data.List`?

**Comment by phadej** [comment]
To group `NewType` you need to write `Grouping` instance. What kind of instance you had?

@ekmett is there a reason why `Grouping` doesn't have `Eq` (and `Sorting` doesn't have `Ord`) as their superclasses? Is there some instances which would be excluded?

**Comment by alexloomis** [comment]
This was a year and a half ago, so I don't remember the specific context, but I believe `Grouping` was derived automatically. I'm looking through my git commits for that day, and it looks like the issue may have been code of the form

```haskell
newtype NewType = NewType (Int, Int)
  deriving (Generic, Grouping)
instance Eq newType where
  NewType (a,_) == NewType (b,_) = a == b
```

**Comment by phadej** [comment]
Here, `Grouping` and `Eq` disagree. To have non-structural `Grouping`, you'll need to write the instance by hand (as you don't derive `Eq` either).

**Comment by alexloomis** [comment]
That makes sense, thanks!

**Comment by ekmett** [comment]
This, as I recall it was the (weak) reason why we don't have an `Eq` superclass. `Grouping` can't be derived automatically to match `Eq`, it just computes itself structurally. If you have a structural `Eq` instance, then `Grouping` will match.

If not, you can manually implement it to match.
