### ISSUE TITLE
Broken links on hackage

### ISSUE THREAD

**Issue by jbmccarty** [ekmett/discrimination#53]
Hi, the links to Fritz Henglein's papers and homepage produce 404s. I think his homepage might have moved [here](https://di.ku.dk/english/staff/?pure=en/persons/14770). I haven't been able to find a new source for the linked papers without knowing their titles, though.

**Comment by RyanGlScott** [comment]
The `README` updated its hyperlinks in https://github.com/ekmett/discrimination/pull/14. We should copy the new URLs over to the `.cabal` file (which is what is shown on Hackage) as well.

**Comment by RyanGlScott** [comment]
Fixed in https://github.com/ekmett/discrimination/commit/287d9cfab08ac45770e05dc9bf2bdf014caa2b6c. I've also applied a [corresponding Hackage revision](https://hackage.haskell.org/package/discrimination-0.5/revisions/) so that the new URLs show up on Hackage.

**Comment by jbmccarty** [comment]
Thanks!
